### ISSUE TITLE
UIDocumentView not available in Unity 2020.

### ISSUE THREAD

**Issue by bgulanowski** [JochenHeckl/DataBinding#1]
**Describe the bug**

Compiler error in UIDocumentView.

`Library/PackageCache/de.jochenheckl.unity.databinding@213b9ca09b/Runtime/Scripts/UIDocumentView.cs(11,30): error CS0246: The type or namespace name 'UIDocument' could not be found (are you missing a using directive or an assembly reference?)`

**To Reproduce**

Attempt to add package to Unity 2020, any verison.

**Expected behavior**
No compiler errors.

**Comment by JochenHeckl** [comment]
Thanks for the report @bgulanowski.

I was aware of this problem and therefore I raised the minimal Unity version requirement of this package to 2021.2.
You can still use this package with older versions of Unity that does not include UIToolkit [(or UIElements - as it is was called before)](https://forum.unity.com/threads/renaming-uielements-to-ui-toolkit.854245/) however. To do this you have to manually add a reference to the package:

- Open The Package Manager
- Click + button and select: Add package from git URL...
- type "com.unity.ui"
- Click "Add"

The compiler errors should be gone.
