### ISSUE TITLE
Installing for source

### ISSUE THREAD

**Issue by mercurial-moon** [JochenHeckl/DataBinding#4]
Hi,
How do  we install this library from source, I downloaded the zip from the repository, but have no idea how to proceed, do I need to compile it before including it into the unity project?

**Comment by JochenHeckl** [comment]
You can [install the package from a git URL](https://docs.unity3d.com/Manual/upm-ui-giturl.html).
Just follow the step by step tutorial.

**Comment by mercurial-moon** [comment]
Yes, however I don't have access to git urls on my network, so was hoping if there was someway to do it with the downloaded zip from github.

**Comment by JochenHeckl** [comment]
Well, you can of course just copy the files into your Packages or Assets folder manually. But I would recommend using the package process as it was designed by Unity.
